"""table fix new column

Revision ID: 1dd2a6d06707
Revises: a2501c795cc1
Create Date: 2020-08-14 23:19:26.351990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd2a6d06707'
down_revision = 'a2501c795cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movement', sa.Column('asinfo', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movement', 'asinfo')
    # ### end Alembic commands ###
