"""tables new

Revision ID: 8d7b28365340
Revises: 9de8eaf69154
Create Date: 2020-08-11 18:05:08.253183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7b28365340'
down_revision = '9de8eaf69154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('division',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('barcode', sa.Integer(), nullable=True),
    sa.Column('inv_number', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('asstatus', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_barcode'), 'object', ['barcode'], unique=True)
    op.create_index(op.f('ix_object_inv_number'), 'object', ['inv_number'], unique=True)
    op.create_index(op.f('ix_object_name'), 'object', ['name'], unique=True)
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_index(op.f('ix_worker_token'), 'worker', ['token'], unique=True)
    op.create_table('placement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placement_name', sa.String(length=128), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('placement_id', sa.Integer(), nullable=True),
    sa.Column('from_placement_id', sa.Integer(), nullable=True),
    sa.Column('oid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_placement_id'], ['placement.id'], ),
    sa.ForeignKeyConstraint(['oid'], ['object.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.ForeignKeyConstraint(['placement_id'], ['placement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movement')
    op.drop_table('placement')
    op.drop_index(op.f('ix_worker_token'), table_name='worker')
    op.drop_table('worker')
    op.drop_table('operation')
    op.drop_index(op.f('ix_object_name'), table_name='object')
    op.drop_index(op.f('ix_object_inv_number'), table_name='object')
    op.drop_index(op.f('ix_object_barcode'), table_name='object')
    op.drop_table('object')
    op.drop_table('division')
    # ### end Alembic commands ###
