"""queries add

Revision ID: f9e217ccc347
Revises: 1dd2a6d06707
Create Date: 2020-08-20 15:12:51.049594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e217ccc347'
down_revision = '1dd2a6d06707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'division', ['division_name'])
    op.drop_index('ix_object_name', table_name='object')
    op.create_index(op.f('ix_object_name'), 'object', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_object_name'), table_name='object')
    op.create_index('ix_object_name', 'object', ['name'], unique=1)
    op.drop_constraint(None, 'division', type_='unique')
    # ### end Alembic commands ###
